# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
BASE_IP = "192.168.56.10"
MASTER_IP = "192.168.56.20"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  
  config.vm.define "master" do |master|
    master.vm.box = "centos-65-x64-virtualbox-nocm"
    master.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box"
    master.vm.network :private_network, ip: "#{MASTER_IP}"
    master.vm.hostname = "master.olindata.vm"
    master.vm.provision "shell",
      path: "master_setup.sh"
  end


  config.vm.box = "debian-73-x64-virtualbox-puppet"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/debian-73-x64-virtualbox-puppet.box"
  
  (0..3).each do |i|
    config.vm.define "galera00#{i}" do |galera|
      galera.vm.network :private_network, ip: "#{BASE_IP}#{i}"
      galera.vm.hostname = "galera00#{i}.olindata.vm"
      galera.vm.provision "shell",
        path: "agent_setup.sh"
    end
  end


end
